services:
  - type: web
    name: cozy-coffee-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://order-app-backend-rsla.onrender.com/api
        sync: false
